package protocol;

public enum Command{CREATE_SERVER, SAVE_SERVER_CONFIGURATION, DISCONNECT_MAIN, GET_SERVERS, CHECK_PASSWORD,
    END_MESSAGE, SAVE_TABLE_MAZE, GET_TABLE_MAZE, KILL_SERVER, SEND_TIME, GET_RESULTS, SET_PLAYER_NAME, READY,
    CREATE_PLAYER_ID, GET_SERVER_CONFIG}
